In [27]:
import numpy as np
arr0 = np.array(42)
print(arr0)

42


In [13]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [15]:
import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [37]:
import numpy as np
arr = np.array([[4,5,6],[7,8,9]])
print(arr)

[[4 5 6]
 [7 8 9]]


In [39]:
import numpy as np
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [23]:
print(arr1.ndim)

1


In [29]:
print(arr0.ndim)

0


In [31]:
print(arr2.ndim)

2


In [41]:
print(arr3.ndim)

3


In [43]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])

1


In [47]:
import numpy as np
arr =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,4]) 

10


In [49]:
import numpy as np
arr = np.array([[11,12,13,14,15],[16,17,18,19,20]])
print(arr[0,4])

15


In [53]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])


6


In [61]:
print(arr[1,1,2])

12


In [63]:
print(arr[1,0,1])

8


In [65]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [67]:
import numpy as np
arr=np.array([11,12,13,14,15,16,17,18])
print(arr[2:6])

[13 14 15 16]


In [71]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [73]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
